// Server-side copy of the item catalog (name/stream/explain/shortWhy) — kept in sync with
// outputs/recycling-training.html's ALL_ITEMS by tools/sync-catalog.js (`npm run sync-catalog`).
// Needed so sendMyResultEmail can build real, human-readable per-item feedback text without
// duplicating the catalog by hand.
// AUTO-GENERATED CATALOG START — do not edit by hand, run `npm run sync-catalog` after
  // changing the `ALL_ITEMS` array in recycling-training.html (see tools/sync-catalog.js).
  const catalog = {
    'gw-pizza': {name:'Greasy pizza box', stream:'gw', explain:"Grease and food residue stop paper fibre from being recycled, contaminating a whole batch - that's why a greasy box can't go with clean paper & cardboard. If only one side is stained, the other clean side can be torn off and recycled separately.", shortWhy:"Grease contaminates recyclable batch"},
    'gw-cup': {name:'Disposable coffee cup', stream:'gw', explain:"Disposable cups are lined with plastic to hold liquid, which most facilities can't separate out - that lining rules out ordinary recycling streams unless your building has a dedicated coffee cup collection.", shortWhy:"Plastic lining ruins paper"},
    'gw-mug': {name:'Broken ceramic mug', stream:'gw', explain:"Ceramic melts at a different temperature than glass or plastic and contaminates a whole batch if mixed in - broken ceramics need to stay well away from ordinary recycling.", shortWhy:"Ceramic contaminates recyclables"},
    'gw-chips': {name:'Empty chip packet', stream:'gw', explain:"Shiny or aluminium-lined chip packets are made from multi-layer materials and cannot be recycled, not even through specialised soft-plastics recycling streams.", shortWhy:"Chip packets aren't electronics"},
    'gw-tissue': {name:'Used tissue', stream:'gw', explain:"Even though it's made of paper, once fibre has absorbed liquid or food it can no longer be recycled - a used tissue can't go in with recyclable streams.", shortWhy:"Soiled paper isn't electronic"},
    'mr-bottle': {name:'Empty plastic bottle', stream:'mr', explain:"It's a rigid, empty container - the shape and condition are what matter most here. A quick rinse or shake-out keeps the batch clean; no need for spotless.", shortWhy:"Recyclable, not landfill waste"},
    'mr-jar': {name:'Rinsed glass jar', stream:'mr', explain:"Glass is the key factor here. A rinsed empty glass jar is recyclable through the Mixed Recycling stream.", shortWhy:"Glass recycles, not landfill"},
    'mr-can': {name:'Aluminium can', stream:'mr', explain:"Empty aluminium is valuable and endlessly recyclable - as long as it's empty, a can is exactly the kind of rigid container this stream is built for.", shortWhy:"Metal, not paper fibre"},
    'mr-tin': {name:'Steel tin can', stream:'mr', explain:"Steel and tin cans recycle just like aluminium - rinse out any food residue first so it doesn't contaminate the batch.", shortWhy:"Metal doesn't compost"},
    'mr-tub': {name:'Rinsed takeaway container', stream:'mr', explain:"It's a rinsed takeaway food container made from plastic types 1, 2, or 5 only - empty and dry is all this stream needs from it.", shortWhy:"Plastic container, not electronic"},
    'pc-box': {name:'Flattened cardboard box', stream:'pc', explain:"Clean, dry cardboard is prime paper fibre stock. Flatten it first - it takes a fraction of the space.", shortWhy:"Clean cardboard is recyclable"},
    'pc-paper': {name:'Stack of office paper', stream:'pc', explain:"Dry office paper is core fibre stock - no grease, no food contact, straight into the paper stream.", shortWhy:"Paper isn't a container"},
    'pc-envelope': {name:'Used envelope', stream:'pc', explain:"Envelopes - window plastic and all - are accepted as paper fibre in most facilities, no need to pick anything out.", shortWhy:"Paper, not a container"},
    'pc-newspaper': {name:'Folded newspaper', stream:'pc', explain:"Newspaper is clean, dry fibre - fold it flat, same as any other clean cardboard or paper.", shortWhy:"Recycles better than composting"},
    'pc-tube': {name:'Cardboard tube', stream:'pc', active:false, explain:"An empty cardboard tube is clean paper fibre - treat it just like a flattened box.", shortWhy:"Cardboard, not electronic waste"},
    'pc-shredded': {name:'Shredded paper', stream:'pc', explain:"Shredded paper is still clean paper fibre once it's been through a shredder - it recycles the same as any other paper, though many buildings ask for it in its own bag so the short strips don't scatter and jam sorting equipment.", shortWhy:"Shredded paper still recycles"},
    'og-banana': {name:'Banana peel', stream:'og', explain:"Food scraps like this break down naturally instead of sitting sealed in landfill for years - that's the whole point of a compost stream.", shortWhy:"Compostable, not landfill waste"},
    'og-teabag': {name:'Used tea bag', stream:'gw', active:false, explain:"Most tea bags contain a fine plastic mesh that doesn't break down, which contaminates a compost batch - since the two aren't separated before disposal, the whole bag goes to general waste, not the organics bin.", shortWhy:"Plastic mesh contaminates compost"},
    'og-apple': {name:'Apple core', stream:'og', explain:"Apple cores and other fruit scraps are exactly what a compost stream exists for - they break down naturally instead of sitting in landfill.", shortWhy:"Wet scraps ruin paper"},
    'og-coffee': {name:'Coffee grounds', stream:'og', explain:"Coffee grounds are a natural organic material - they belong in Organics, not General Waste or recycling.", shortWhy:"Damp grounds ruin paper"},
    'og-fish': {name:'Fish scraps', stream:'og', explain:"Fish and other food scraps compost naturally, rather than sitting sealed in a landfill bag for years.", shortWhy:"Food scraps, not electronics"},
    'ew-battery': {name:'Dead battery', stream:'ew', active:false, explain:"Batteries need their own dedicated collection point - separate from the general E-Waste point used for cables, phones, and other electronics. Mixing them in risks a fire in a collection bin or truck.", shortWhy:"Needs its own battery point"},
    'ew-cables': {name:'Tangled cables & charger', stream:'ew', explain:"Cables and chargers are electronics - they need proper recovery, never an ordinary waste or recycling bin.", shortWhy:"Wires need e-waste recovery"},
    'ew-phone': {name:'Cracked phone', stream:'ew', explain:"Phones and other small electronics need a dedicated collection point, cracked or not - the materials inside need proper recovery.", shortWhy:"Electronics, not paper waste"},
    'ew-toner': {name:'Printer toner cartridge', stream:'ew', active:false, explain:"Printer and toner cartridges need their own dedicated collection - most manufacturers run a take-back program for them, separate from the general E-Waste point used for cables, phones, and other electronics. They never belong in an ordinary waste or recycling bin either.", shortWhy:"Needs its own cartridge return point"},
    'ew-mouse': {name:'Computer mouse', stream:'ew', explain:"A mouse is a small electronic, just like cables, phones, and other office electronics - it needs the same dedicated recovery.", shortWhy:"Electronics won't compost"},
    'gw-glass': {name:'Broken drinking glass', stream:'gw', active:false, explain:"Drinking glass is heat-treated to a different melting point than bottle and jar glass, so it contaminates a recycling batch rather than blending in - it needs to go in general waste, broken or not.", shortWhy:"Different glass, contaminates batch"},
    'gw-napkin': {name:'Used paper napkin', stream:'gw', active:false, explain:"Once paper fibre has absorbed food, grease, or liquid it can't be recycled as paper - a used napkin or paper towel belongs with general waste, not with clean paper stock.", shortWhy:"Soiled paper, not clean fibre"},
    'gw-cutlery': {name:'Disposable plastic cutlery', stream:'gw', active:false, explain:"Small, mixed-shape plastic like disposable cutlery falls through sorting screens built for rigid containers, and its light weight and odd shape jam equipment rather than getting sorted - it belongs in general waste.", shortWhy:"Too small, jams sorting equipment"},
    'gw-foam': {name:'Polystyrene foam container', stream:'gw', active:false, explain:"Foam packaging is mostly trapped air and crumbles into tiny beads rather than melting down cleanly - most facilities can't process it, so it belongs in general waste.", shortWhy:"Crumbles, not a real container"},
    'gw-wrap': {name:'Soft plastic wrap', stream:'gw', active:false, explain:"Thin, flexible plastic film stretches and tangles in the machinery that sorts rigid containers - without a dedicated soft-plastics point, it belongs in general waste.", shortWhy:"Soft plastic tangles machinery"},
    'mr-detergent': {name:'Plastic detergent bottle', stream:'mr', active:false, explain:"It's a rigid, empty plastic container - the shape is what matters, not the label. A quick rinse of any leftover residue keeps the batch clean.", shortWhy:"Rigid container, rinse and recycle"},
    'mr-lid': {name:'Loose metal bottle cap', stream:'mr', active:false, explain:"A loose metal cap or lid is small but still a rigid metal container piece - collect it separately from the bottle rather than leaving it on, so sorting equipment can catch it properly.", shortWhy:"Small metal, still recyclable"},
    'mr-carton': {name:'Rinsed milk carton', stream:'mr', active:false, explain:"The wax or foil coating that keeps liquid in is bonded to the cardboard in a way most paper mills can't separate, but the carton's rigid shape means it sorts fine as mixed recycling once rinsed.", shortWhy:"Coated carton, not plain paper"},
    'mr-foiltray': {name:'Aluminium foil tray', stream:'mr', active:false, explain:"Clean aluminium foil and foil trays are valuable, endlessly-recyclable metal - scrunching loose foil into a rinsed tray or ball helps it survive sorting instead of slipping through as litter.", shortWhy:"Clean metal, recycles well"},
    'mr-aerosol': {name:'Empty aerosol can', stream:'mr', active:false, explain:"A fully empty aerosol can is rigid metal like any other tin - the pressurised contents are the hazard, not the empty container, so once it's spent it recycles the same as a steel tin.", shortWhy:"Empty can, metal recycles"},
    'pc-magazine': {name:'Glossy magazine', stream:'pc', active:false, explain:"Glossy paper is still paper fibre once the ink and coating are pulped out at the mill - magazines and glossy flyers recycle right alongside plain paper.", shortWhy:"Glossy paper still pulps fine"},
    'pc-junkmail': {name:'Junk mail flyer', stream:'pc', active:false, explain:"Junk mail and flyers are plain paper - no need to shred or sort by sender first, they go straight in with the rest of your paper and cardboard.", shortWhy:"Plain paper, no shredding needed"},
    'pc-eggcarton': {name:'Cardboard egg carton', stream:'pc', active:false, explain:"Moulded pulp egg cartons are just pressed paper fibre, no coating or lining - they break back down with the rest of your cardboard once flattened.", shortWhy:"Pressed paper fibre, no coating"},
    'pc-notebook': {name:'Spiral notebook', stream:'pc', active:false, explain:"The paper pages recycle just like any other office paper - the small metal spiral binding is separated out automatically at the recycling facility, no need to remove it yourself.", shortWhy:"Paper pages, binding sorts out"},
    'pc-giftwrap': {name:'Plain paper gift wrap', stream:'pc', active:false, explain:"Plain paper gift wrap - no foil, glitter, or plastic coating - recycles the same as any other sheet of paper, once any tape is torn off.", shortWhy:"Plain paper, tape removed first"},
    'og-eggshell': {name:'Egg shells', stream:'og', explain:"Egg shells break down quickly and add useful minerals to compost - crushing them first helps them decompose even faster.", shortWhy:"Breaks down fast, adds minerals"},
    'og-breadcrust': {name:'Stale bread crust', stream:'og', active:false, explain:"Bread and other baked goods break down quickly as food waste - stale or mouldy is still compostable, no need to wait until it's fresh.", shortWhy:"Food scraps, compost fine stale"},
    'og-veggie': {name:'Vegetable peelings', stream:'og', active:false, explain:"Vegetable peelings and trimmings are food scraps like any other - they compost quickly and add nutrients back into the soil.", shortWhy:"Food scraps, compost naturally"},
    'og-flowers': {name:'Wilted flowers', stream:'og', active:false, explain:"Wilted flowers and plant trimmings are green waste - they break down naturally as organic matter, the same as food scraps.", shortWhy:"Green waste, breaks down naturally"},
    'og-ricepasta': {name:'Leftover rice or pasta', stream:'og', active:false, explain:"Cooked leftovers like rice or pasta are food scraps just like any other meal waste - they compost fine, plate scrapings included.", shortWhy:"Cooked food scraps, compostable"},
    'ew-keyboard': {name:'Computer keyboard', stream:'ew', active:false, explain:"A keyboard is small electronics like any other - the circuitry inside needs the same dedicated recovery as cables, phones, and other office electronics.", shortWhy:"Circuitry needs e-waste recovery"},
    'ew-remote': {name:'Broken remote control', stream:'ew', active:false, explain:"A remote control is small electronics with a circuit board inside, just like a mouse or keyboard - it needs proper e-waste recovery, not the household bin (remove any batteries first).", shortWhy:"Circuit board, not household waste"},
    'ew-headphones': {name:'Broken headphones', stream:'ew', active:false, explain:"Headphones and earbuds contain small speakers and wiring - the same kind of electronic materials as cables and phones, needing the same dedicated recovery.", shortWhy:"Small speakers, e-waste recovery"},
    'ew-speaker': {name:'Desktop speaker', stream:'ew', active:false, explain:"A desktop speaker has a magnet and wiring coil inside - genuine electronic components that need dedicated recovery, not the general bin.", shortWhy:"Magnet and coil, needs recovery"},
    'ew-powerboard': {name:'Power board', stream:'ew', active:false, explain:"A power board or extension cord is electrical wiring and switches, the same category as chargers and cables - it needs dedicated e-waste recovery, not the general bin.", shortWhy:"Wiring and switches, not general bin"},
    'ew-printer': {name:'Printer', stream:'ew', explain:"A printer is an electronic device with circuitry and moving parts inside, the same category as other office electronics - it needs dedicated e-waste recovery, not the general bin.", shortWhy:"Electronic device, needs recovery"},
    'ew-monitor': {name:'Computer monitor', stream:'ew', explain:"A computer monitor contains circuitry and screen components, the same category as other electronics - it needs dedicated e-waste recovery, not the general bin.", shortWhy:"Screen electronics, needs recovery"}
  };
  // AUTO-GENERATED CATALOG END

module.exports = { catalog };
